#!/usr/bin/env bash
VERSION="0.3.1"

set -euo pipefail

CURRENT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMODULE_DIR="$(dirname "$CURRENT_PATH")"
SUBMODULE_NAME="$(basename "$SUBMODULE_DIR")"
PROJECT_ROOT="$(dirname "$SUBMODULE_DIR")"
LIB_DIR="$PROJECT_ROOT/lib"

source "$SUBMODULE_DIR/lib/std/import.sh"

import std/init
import core/args
import ext/select

main() {
	args.init 构建开发环境
	args.add_options "version" "v" "显示版本信息"

	args.process "$@"
	args.has "-v" "--version" && usage.version && exit 0

	mkdir -p "$LIB_DIR"/ext
	cd "$PROJECT_ROOT"
	[[ ! -d lib/core ]] && ln -rsfn "$SUBMODULE_NAME/lib/core" lib/
	[[ ! -d lib/std ]] && ln -rsfn "$SUBMODULE_NAME/lib/std" lib/

	if selected=$(select.multi "选择要安装的扩展模块" "$SUBMODULE_NAME"/lib/ext/*.sh); then
		for f in $selected; do
			ln -rsfn "$f" lib/ext
		done
	fi

	[[ ! -f "main.sh" ]] && cp "$SUBMODULE_NAME/examples/main.sh" ./
	[[ ! -f "config.toml" ]] && touch config.toml
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
		main "$@"
fi
